### PR TITLE
Add support for analytics of websites

### LINKED ISSUE #25: Add support for analytics of websites

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Used by
https://github.com/BuroHappoldEngineering/BuildingPerformanceForm_Tool/pull/1

   
### Issues addressed by this PR

Closes #25

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check project-compliance
@BHoMBot check documentation-compliance

**Comment by adecler** [comment]
project-compliance
documentation-compliance

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@BHoMBot check core

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@BHoMBot check compliance

**Comment by adecler** [comment]
@BHoMBot fix copyright headers ref. 4862460326

**Comment by adecler** [comment]
@BHoMBot check compliance

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@BHoMBot check core

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@al-fisher , it would be great to get this merged alongside the PR for the [BuildingPerformance website](https://github.com/BuroHappoldEngineering/BuildingPerformanceForm_Tool/pull/1). 
FYI, I have checked that the database is still receiving the data and all seems to be working.

**Comment by adecler** [comment]
@BHoMBot check copyright-compliance

**Review by FraserGreenroyd — APPROVED** [review]
I'm happy with these changes, brings in the analytics for web usage and is being seen on the databases as remarked by @adecler so would have no qualms with this being merged in.

**Pull request merged**
