### PR TITLE
Add link to project database for analytics

### LINKED ISSUE #43: Connect analytics with project database
Connect the analytics project capturing with the project database to allow users to filter to their project without needing to know all of the project numbers.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #43 

### Test files
N/A

Steps to test:

1. Be connected to the VPN or on network
2. On this PR, load a script that will trigger the pop-up
3. See that the project ID input is now a filterable combo-box
4. Try filtering to a known project - for the benefits of testing use `0000000` project ID if you wish to test the confirm option
5. Try entering a new project ID (one that isn't filterable) to see that new projects can be input

Second test:

1. Be not connected to the VPN or on network
2. Test that you can input a project ID as previous without any errors from not being able to access the project database

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 8675863275

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by travispotterBH** [comment]
Popup loading time is noticeably longer with the inclusion of this functionality. I suspect this is due to the need to load up the project data from the database. I suggest a form of caching, but am unsure how to implement this where it would meet both the requirements to have up-to-date project data and have shorter loading times. 
https://github.com/BHoM/BHoMAnalytics_Toolkit/issues/46

There appears to be a bug where typing speed above ~50wpm will cause the filter to reset while searching. 
https://github.com/BHoM/BHoMAnalytics_Toolkit/issues/45

It would be nice to have the projects separated by active/inactive/dormant status. Suggest that active projects appear in the standard filter background color, and inactive/dormant projects appear "greyed out" or indicated to be different in some way more readily apparent by choice of color/shading/indentation/etc. 
https://github.com/BHoM/BHoMAnalytics_Toolkit/issues/47


I think this is a nice feature addition and am prepared to approve this PR, provided that the items above are set as bug/feature request issues to addressed  prior to the release of 6.0.

**Comment by FraserGreenroyd** [comment]
@travispotterBH thanks for the review, I'm happy to pick up #45 and #46 in a new PR or 2, with #47 possibly being handled by what I'll do for #46. I think if we deploy this via alpha, we can start to get some user feedback as well while we then work on #45/#46 :smile:

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
