### PR TITLE
Remove dependency on BHoM_UI

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### NOTE: Depends on 
https://github.com/BHoM/BHoM/pull/1598
https://github.com/BHoM/BHoM_UI/pull/480

   
### Issues addressed by this PR
Fixes https://github.com/BHoM/BHoMAnalytics_Toolkit/issues/73

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation
@BHoMBot check copyright-compliance
@BHoMBot check null-handling
@BHoMBot check documentation-compliance
@BHoMBot check project-compliance

**Review by Tom-Kingstone — APPROVED** [review]
Approval based off my review on linked PR

**Comment by Tom-Kingstone** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
