### PR TITLE
Tidy up the repository

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Tidies up the repository

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Review by travispotterBH — APPROVED** [review]
Changes are necessary for desired outcome.

**Comment by travispotterBH** [comment]
@BHoMBot  check ready-to-merge

**Comment by adecler** [comment]
What's the context of this PR ? Can you add the link to the issue it relates to ?

**Pull request merged**
