### PR TITLE
Add username property to UsageEntry

### LINKED ISSUE #85: Add username property to UsageEntry
#### Description:
On top of the ComputerID, also capture the user login

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Fixes #85 

This adds the capture of the username on top of the computer ID.

### Test files
After compiling this code, make sure to use one of our BHoM UIs. This will generate new log files that will be pushed to our database.

To test that this worked, you can connect to the Mongo database to check that the entries are now containing your username.
The simplest Mongo query to check the result is `db.getCollection("UsageData").find({}).sort({_id: -1})` .

### CODE REVIEW

**Review by michaelhoehn — APPROVED** [review]
Have tested and verified that both username and computer are coming through as expected. Happy to approve. LGTM 👍

**Comment by adecler** [comment]
@BHoMBot check compliance

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Comment by adecler** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
